/**
 * Sous-liste CIM-10 de depart (F-ADM-04, F-CLI-06 du pack) : diagnostics
 * frequents en soins primaires et codes des groupes de la section 18.6. Le
 * pack en prevoit environ 200 ; celle-ci en compte une centaine, a completer
 * par l'administration. Fichier SANS "use server".
 *
 * Contenu de developpement et de demonstration : libelles resumes, a faire
 * valider par les autorites sanitaires avant tout usage reel (avertissement
 * de la section 18.4 du pack). Groupe, chapitre et caractere sensible de
 * chaque code se deduisent du code (cim10-groupes.ts) au moment du semis.
 */

export const DIAGNOSTICS_CIM10_PAR_DEFAUT: { code: string; libelle: string }[] = [
  { code: "A00.9", libelle: "Choléra, sans précision" },
  { code: "A01.0", libelle: "Fièvre typhoïde" },
  { code: "A03.9", libelle: "Shigellose, sans précision" },
  { code: "A06.0", libelle: "Dysenterie amibienne aiguë" },
  { code: "A09", libelle: "Diarrhée et gastro-entérite d'origine présumée infectieuse" },
  { code: "A15", libelle: "Tuberculose de l'appareil respiratoire, avec confirmation bactériologique et histologique" },
  { code: "A16", libelle: "Tuberculose de l'appareil respiratoire, sans confirmation bactériologique ou histologique" },
  { code: "A30", libelle: "Lèpre" },
  { code: "A33", libelle: "Tétanos néonatal" },
  { code: "A35", libelle: "Autres formes de tétanos" },
  { code: "A36", libelle: "Diphtérie" },
  { code: "A37", libelle: "Coqueluche" },
  { code: "A39", libelle: "Infection à méningocoques" },
  { code: "A41.9", libelle: "Septicémie, sans précision" },
  { code: "A50", libelle: "Syphilis congénitale" },
  { code: "A53.9", libelle: "Syphilis, sans précision" },
  { code: "A54", libelle: "Infection gonococcique" },
  { code: "A56", libelle: "Autres infections à Chlamydia transmises par voie sexuelle" },
  { code: "A60", libelle: "Infection anogénitale par le virus de l'herpès" },
  { code: "A64", libelle: "Maladie sexuellement transmise, sans précision" },
  { code: "A82", libelle: "Rage" },
  { code: "A90", libelle: "Dengue" },
  { code: "A95", libelle: "Fièvre jaune" },
  { code: "A96.2", libelle: "Fièvre de Lassa" },
  { code: "A98.4", libelle: "Maladie à virus Ebola" },
  { code: "B01", libelle: "Varicelle" },
  { code: "B05", libelle: "Rougeole" },
  { code: "B06", libelle: "Rubéole" },
  { code: "B15", libelle: "Hépatite aiguë A" },
  { code: "B16", libelle: "Hépatite aiguë B" },
  { code: "B18", libelle: "Hépatite virale chronique" },
  { code: "B20", libelle: "Maladie due au VIH, à l'origine de maladies infectieuses et parasitaires" },
  { code: "B24", libelle: "Maladie due au VIH, sans précision" },
  { code: "B26", libelle: "Oreillons" },
  { code: "B35", libelle: "Dermatophytose" },
  { code: "B50", libelle: "Paludisme à Plasmodium falciparum" },
  { code: "B51", libelle: "Paludisme à Plasmodium vivax" },
  { code: "B54", libelle: "Paludisme, sans précision" },
  { code: "B65", libelle: "Schistosomiase [bilharziose]" },
  { code: "B76", libelle: "Ankylostomiase" },
  { code: "B77", libelle: "Ascaridiase" },
  { code: "B86", libelle: "Gale" },
  { code: "D50", libelle: "Anémie par carence en fer" },
  { code: "D57", libelle: "Affections drépanocytaires" },
  { code: "D64.9", libelle: "Anémie, sans précision" },
  { code: "E10", libelle: "Diabète sucré de type 1" },
  { code: "E11", libelle: "Diabète sucré de type 2" },
  { code: "E14", libelle: "Diabète sucré, sans précision" },
  { code: "E40", libelle: "Kwashiorkor" },
  { code: "E41", libelle: "Marasme nutritionnel" },
  { code: "E43", libelle: "Malnutrition protéino-énergétique grave, sans précision" },
  { code: "E44", libelle: "Malnutrition protéino-énergétique de degré moyen et léger" },
  { code: "E46", libelle: "Malnutrition protéino-énergétique, sans précision" },
  { code: "E66", libelle: "Obésité" },
  { code: "F10", libelle: "Troubles mentaux et du comportement liés à l'utilisation d'alcool" },
  { code: "F17", libelle: "Troubles mentaux et du comportement liés à l'utilisation de tabac" },
  { code: "F20", libelle: "Schizophrénie" },
  { code: "F32", libelle: "Épisode dépressif" },
  { code: "F41", libelle: "Autres troubles anxieux" },
  { code: "G00", libelle: "Méningite bactérienne, non classée ailleurs" },
  { code: "G40", libelle: "Épilepsie" },
  { code: "G43", libelle: "Migraine" },
  { code: "I10", libelle: "Hypertension essentielle (primitive)" },
  { code: "I11", libelle: "Cardiopathie hypertensive" },
  { code: "I25", libelle: "Cardiopathie ischémique chronique" },
  { code: "I50", libelle: "Insuffisance cardiaque" },
  { code: "I64", libelle: "Accident vasculaire cérébral, non précisé comme étant hémorragique ou par infarctus" },
  { code: "J00", libelle: "Rhinopharyngite aiguë [rhume banal]" },
  { code: "J02", libelle: "Pharyngite aiguë" },
  { code: "J03", libelle: "Amygdalite aiguë" },
  { code: "J06", libelle: "Infections aiguës des voies respiratoires supérieures, à localisations multiples et non précisées" },
  { code: "J15", libelle: "Pneumopathie bactérienne, non classée ailleurs" },
  { code: "J18", libelle: "Pneumopathie, micro-organisme non précisé" },
  { code: "J20", libelle: "Bronchite aiguë" },
  { code: "J22", libelle: "Infection aiguë des voies respiratoires inférieures, sans précision" },
  { code: "J44", libelle: "Autres maladies pulmonaires obstructives chroniques" },
  { code: "J45", libelle: "Asthme" },
  { code: "K29", libelle: "Gastrite et duodénite" },
  { code: "K35", libelle: "Appendicite aiguë" },
  { code: "K59", libelle: "Autres troubles fonctionnels de l'intestin" },
  { code: "K80", libelle: "Cholélithiase" },
  { code: "L02", libelle: "Abcès cutané, furoncle et anthrax" },
  { code: "L03", libelle: "Phlegmon" },
  { code: "L08", libelle: "Autres infections localisées de la peau et du tissu cellulaire sous-cutané" },
  { code: "L20", libelle: "Dermite atopique" },
  { code: "M54", libelle: "Dorsalgie" },
  { code: "N18", libelle: "Maladie rénale chronique" },
  { code: "N39.0", libelle: "Infection des voies urinaires, siège non précisé" },
  { code: "N76", libelle: "Autres affections inflammatoires du vagin et de la vulve" },
  { code: "O00", libelle: "Grossesse extra-utérine" },
  { code: "O03", libelle: "Avortement spontané" },
  { code: "O04", libelle: "Avortement médical" },
  { code: "O14", libelle: "Hypertension gestationnelle avec protéinurie significative" },
  { code: "O20", libelle: "Hémorragie du début de la grossesse" },
  { code: "O21", libelle: "Vomissements au cours de la grossesse" },
  { code: "O23", libelle: "Infections des voies génito-urinaires au cours de la grossesse" },
  { code: "O42", libelle: "Rupture prématurée des membranes" },
  { code: "O72", libelle: "Hémorragie du post-partum" },
  { code: "O80", libelle: "Accouchement unique et spontané" },
  { code: "O82", libelle: "Accouchement unique par césarienne" },
  { code: "P07", libelle: "Troubles liés à une durée de gestation courte et à un poids de naissance faible" },
  { code: "P22", libelle: "Détresse respiratoire du nouveau-né" },
  { code: "P36", libelle: "Septicémie bactérienne du nouveau-né" },
  { code: "R05", libelle: "Toux" },
  { code: "R10", libelle: "Douleur abdominale et pelvienne" },
  { code: "R11", libelle: "Nausées et vomissements" },
  { code: "R50.9", libelle: "Fièvre, sans précision" },
  { code: "R51", libelle: "Céphalée" },
  { code: "R53", libelle: "Malaise et fatigue" },
  { code: "S06", libelle: "Lésion traumatique intracrânienne" },
  { code: "S52", libelle: "Fracture de l'avant-bras" },
  { code: "S82", libelle: "Fracture de la jambe, y compris la cheville" },
  { code: "T14.9", libelle: "Traumatisme, sans précision" },
  { code: "T30", libelle: "Brûlure et corrosion, partie du corps non précisée" },
  { code: "T63", libelle: "Effet toxique d'un contact avec un animal venimeux" },
  { code: "T74", libelle: "Syndromes dus à de mauvais traitements" },
  { code: "Y05", libelle: "Agression sexuelle par la force physique" },
  { code: "Y07", libelle: "Autres syndromes de maltraitance" },
  { code: "Z00", libelle: "Examen général et investigations de sujets sans plainte ni diagnostic rapporté" },
  { code: "Z21", libelle: "Infection asymptomatique par le virus de l'immunodéficience humaine [VIH]" },
  { code: "Z23", libelle: "Nécessité d'une vaccination contre une seule maladie bactérienne" },
  { code: "Z30", libelle: "Prise en charge d'une contraception" },
  { code: "Z34", libelle: "Surveillance d'une grossesse normale" },
];
